#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d                   

# Scratchpad
bspc rule -a kitty sticky=on state=floating rectangle=960x480+180+140

# Borders
bspc config border_width         1
bspc config window_gap           6
bspc config top_padding          25
bspc config normal_border_color "#b16286"
bspc config active_border_color "#987la"
bspc config focused_border_color "#d65d0e"
bspc config presel-feedback_color "#d65d0e"

bspc config split_ratio          0.52

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Motrix state=floating desktop='^4'
bspc rule -a org.gnome.Nautilus state=floating rectangle=1000x580+180+60

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Mouse movements
bspc config click_to_focus          true
bspc config focus_follows_pointer   true

#Autostart
picom &
nitrogen --set-zoom-fill --random ~/Pictures/wallpapers --save &
$HOME/.config/polybar/launch.sh
