require('plugins')
require('options')
require('n-vimtree-cfg')
require('lualine-config')
require('bufferline-config')
require('autopairs-cfg')
require('keybindings')
require('treesitter-cfg')
require('whichkey-config')
require('telescope-config')
vim.cmd('colorscheme gruvbox')

