#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected="$1"
else
    selected=$(find ~/Downloads/dotfiles -mindepth 2 -type f | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

nvim "$selected"

