require('plugins')
require('options')
require('n-vimtree-cfg')
require('lualine-config')
require('bufferline-config')
require('autopairs-cfg')
require('keybindings')
require('treesitter-cfg')
require('whichkey-config')
require('telescope-config')
require('colorizer-config')
require('gitsigns-config')
require('lsp')
require('blankline-config')
require('toggleterm-config')
require('comment-config')
vim.cmd('colorscheme gruvbox')

-- Remaps of keys 
vim.api.nvim_set_keymap('n', '0', '^', { noremap = true, silent = true })
